import streamlit as st
import requests
import json

st.set_page_config(page_title="Text 2 Img by PS333", page_icon="🧠", layout="centered")
st.image("https://i.ibb.co/5Wp2sxxn/1000319964-removebg-preview.png", width=250)
st.title("🔥 PS333 Image Generator 🔥")

prompt = st.text_input("Enter your prompt", placeholder="E.g. A cyberpunk city at night")
style = st.selectbox("Select Image Style", ["Realistic", "Anime", "Fantasy", "Cyberpunk", "Cartoon", "Photorealistic"])

if st.button("✨ Generate Image"):
    if not prompt.strip():
        st.warning("Please enter a valid prompt.")
    else:
        with st.spinner("⏳ Generating your image..."):
            try:
                payload = {
                    "prompt": f"{style} style {prompt}",
                    "params": {
                        "steps": 30,
                        "cfg_scale": 7.0,
                        "sampler_name": "k_euler"
                    }
                }
                headers = {"Content-Type": "application/json"}
                r = requests.post("https://stablehorde.net/api/v2/generate/async", headers=headers, data=json.dumps(payload))
                j = r.json()
                job_id = j.get("id")

                if not job_id:
                    st.error("Failed to start generation.")
                else:
                    # Polling until done
                    image_url = None
                    for _ in range(30):
                        r2 = requests.get(f"https://stablehorde.net/api/v2/generate/status/{job_id}")
                        j2 = r2.json()
                        if j2.get("done") and j2.get("generations"):
                            image_url = j2["generations"][0]["img"]
                            break

                    if image_url:
                        st.image(image_url, use_container_width=True, caption="Generated by ਪ੍ਰਭਵੀਰ ਸਿੰਘ Ai")
                        st.success("✅ Image created!")
                        st.markdown(f"🔗 [Open Full Image]({image_url})")
                        st.download_button(
                            label="📥 Download Image",
                            data=requests.get(image_url).content,
                            file_name="generated_image.png",
                            mime="image/png"
                        )
                    else:
                        st.error("❌ Generation timed out. Try again.")

            except Exception as e:
                st.error(f"Error: {e}")

st.markdown("---")
st.markdown(
    '🔧 Made with ❤️ by [**PS333**](https://instagram.com/prabhveersingh01) | 🔥 Powered by **PS333 AI Studio**'
)
