import streamlit as st
import requests

# --- Page config ---
st.set_page_config(
    page_title="Text 2 Img by PS333",
    page_icon="🧠",
    layout="centered"
)

# --- Header ---
st.image("https://i.ibb.co/5Wp2sxxn/1000319964-removebg-preview.png", width=250)
st.title("🔥 PS333 Image Generator 🔥")

# --- Prompt Input ---
prompt = st.text_input("Enter your prompt", placeholder="E.g. A majestic lion in a futuristic city")

# --- Style Input (optional) ---
style = st.selectbox("Select Image Style", ["Realistic", "Anime", "Fantasy", "Cyberpunk", "Cartoon", "Photorealistic"])

# --- Generate Image ---
if st.button("✨ Generate Image"):
    if prompt.strip() == "":
        st.warning("Please enter a valid prompt.")
    else:
        with st.spinner("⏳ Generating your image..."):
            try:
                # Using Stable Diffusion API (No auth needed)
                response = requests.post(
                    "https://stablediffusionapi.com/api/v3/text2img",
                    json={
                        "prompt": f"{style} style {prompt}",
                        "negative_prompt": "",
                        "width": "512",
                        "height": "512",
                        "samples": "1",
                        "num_inference_steps": "30",
                        "guidance_scale": 7.5
                    }
                )

                result = response.json()
                image_url = result["output"][0]

                st.image(image_url, use_container_width=True, caption="Generated by ਪ੍ਰਭਵੀਰ ਸਿੰਘ Ai")
                st.success("✅ Image created!")
                st.markdown(f"🔗 [Open Full Image]({image_url})")

                # Download button
                st.download_button(
                    label="📥 Download Image",
                    data=requests.get(image_url).content,
                    file_name="generated_image.png",
                    mime="image/png"
                )

            except Exception as e:
                st.error(f"Something went wrong: {e}")

# --- Footer ---
st.markdown("---")
st.markdown(
    '🔧 Made with ❤️ by [**PS333**](https://instagram.com/prabhveersingh01) | 🔥 Powered by **PS333 AI Studio**'
)
